language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
  - CI=true
  global:
  - secure: "process.env.KEY"
deploy:
  provider: heroku
  api_key:
    secure: "process.env.KEY"
  app: safe-earth-19588
  on:
    repo: Aaron-Lathrop/react-hot-cold-testing
